### ISSUE TITLE
Error occurred with lab selection while script is running

### ISSUE THREAD

**Issue by hpoonz** [RamyE/SFU_ML#12]
Hi, we're getting the error occurred with lab selection message even though we have the auto run setup for the script. We manually ran the script in the pi as well but we still get the same error. There are also two other error messages we get at the same time: Processing has failed or was interrupted, and Resetting the serial state of RPi Failed, please try again or power cycle the RPi if the problem persists.

![gui error](https://user-images.githubusercontent.com/55219970/110263516-d19eb700-7f6b-11eb-85b1-a2093c0811b9.PNG)

![gui ssh error](https://user-images.githubusercontent.com/55219970/110263533-debba600-7f6b-11eb-9048-8dd0afbe4bfd.PNG)

**Comment by RamyE** [comment]
can you confirm you're connected to the right serial port? (maybe check the port names in the device manager)

**Comment by hpoonz** [comment]
There's only one serial port for me to select. COM 1 is the only port showing under device manager whether I have the pi connected or not.

**Comment by RamyE** [comment]
if it shows up when the pi is not connected then it is not the pi's serial port. Did u use the same pi & cable & PC when u did lab 1?

**Comment by hpoonz** [comment]
Yes, I had the same error messages from this pc in lab 1. I connected the pi to different ports until I got one showing up as working but now I'm getting some error messages that don't really seem consistent.

The first error I got is this buffer dtype error when I wasn't in the 32 bit conda setup I had.

![buffer dtype error](https://user-images.githubusercontent.com/55219970/110266615-07936980-7f73-11eb-95c5-55c22fbfc3ab.PNG)

After I switched to ml_course_32 I got this error.

![failed to load required model](https://user-images.githubusercontent.com/55219970/110266706-3a3d6200-7f73-11eb-82ab-c2008692e06e.PNG)

When I try running it again now I get the buffer dtype error happening and it switches randomly between the two error messages.

**Comment by RamyE** [comment]
Sounds like the buffer dtype is still the issue here, please confirm that you trained the model using a 32-bit architecture.
You can try something like this in your script on NB where you save the trained model
`import platform; print(platform.architecture())`

**Comment by hpoonz** [comment]
We fiexed the issue. For some reason visual studio code wasn't outputting the model as 32 bit from a 32 bit environment but running it through cmd did.
