### ISSUE TITLE
Persistent Error after fix: Buffer dtype mismatch, expected 'const ITYPE_t' but got 'long long'

### ISSUE THREAD

**Issue by calvin-tse** [RamyE/SFU_ML#19]
I followed the steps in the notes to create 32 bit python environment called ml_course_32 but the error still persists, are there any other ways to fix this error or am I doing something wrong? I followed the following steps:

To do that you can create a new conda environment for that using conda create -n ml_course_32 then activate it conda activate ml_course_32 then set the environment to accept 32 bit packages only using conda config --env --set subdir win-32 and then install python using conda install python=3.7 and then install the required packages for each lab as needed including conda install scikit-learn

The only things I changed is using "conda install python=3.9" because thats the most up to date and I updated the requirements.txt install file to the following because I thought the originals were out of date:
pandas==1.1.3
matplotlib==3.5.1
crccheck==1.0
numpy==1.22.0
pyserial==3.5
PySide2==5.15.2
scikit_learn

![Capture](https://user-images.githubusercontent.com/100800185/156646423-18d24738-76f9-45bd-9f37-87b31986ad65.PNG)

**Comment by RamyE** [comment]
The 32-bit environment is needed to train the model and export it, you
don't (and probably shouldn't) use it to run the GUI, you don't need to
install the "requirements" package in the 32-bit environment, only install
what you need to train the model.

**Comment by Cealjig** [comment]
Could you provide more details about how to train and export the model in the 32-bit environment? I have the same issue and I haven't been able to solve it. I tried adding the environment to my Jupyter Notebook as a new kernel, but once I want to run the code there are some errors regarding missing modules. I would really appreciate if you could provide any assistance with this, and I thank you in advance for your time.

**Comment by RamyE** [comment]
> Could you provide more details about how to train and export the model in the 32-bit environment? I have the same issue and I haven't been able to solve it. I tried adding the environment to my Jupyter Notebook as a new kernel, but once I want to run the code there are some errors regarding missing modules. I would really appreciate if you could provide any assistance with this, and I thank you in advance for your time.

You can activate that environment separately in a terminal and install the missing modules
