### ISSUE TITLE
Error in running RPi script

### ISSUE THREAD

**Issue by cybrkatt** [RamyE/SFU_ML#20]
When attempting to use the GUI it gives the error "Caught exception: write timeout", indicating that the RPi script is not running. This seems to be the case, but when I attempt to run it manually, I get an error with the code.
"ModuleNotFoundError: No module named 'serial'"
I tried to use "pip install pyserial" on the RPi to try and fix this but I get the error "-bash: pip: command not found"
Did I just miss the step adding serial to the RPi?

**Comment by RamyE** [comment]
Please try all the steps in section 1.5 of the manual again and let me know how it goes

**Comment by RamyE** [comment]
Also please provide screenshots as it is useful for me to see how you're trying to run the script manually, etc..

**Comment by cybrkatt** [comment]
Hi,
Thanks for the help, I was able to fix it!
