### ISSUE TITLE
Default opener for main.py

### ISSUE THREAD

**Issue by taffs08** [RamyE/SFU_ML#24]
Hi Ramy, I'm trying to open the GUI , but my laptop changed the default opener of .py files to Notepad. 
Which progeram file should I assign as default opener so it to opens as required?
![issue](https://user-images.githubusercontent.com/101284094/162649978-3c4a8b12-bc77-487e-a395-5fc3d4c13a5c.PNG)

**Comment by RamyE** [comment]
You can follow the steps here https://github.com/RamyE/SFU_ML/blob/master/Ui_project/manual.md#23-run-but-dont-run-away
Simply use `python main.py` but in the right folder, not the one in the screenshot. Also, you will need to have the virtual environment activated

**Comment by taffs08** [comment]
Thanks, I was able to open it in the right folder.
