### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by AshkanTavassoli** [RamyE/SFU_ML#3]
Please pass the exception message when using try/except.
I am getting an error while loading a model in SFU_ML/RPi_Script/utils/piexecuter.py (I am guessing line 142 because I get the error message on line 148) and since there is no logging or no sign of the exception message I have no idea why this is happening.
The model is dumped using pickle. And as I see in this file pickle.load is used so I do not see an issue here.
I also believe any changes to the codes in raspberry pi causes the program to stop working because I tried to modify it to add logging on local raspberry repo and it stopped working.
Anyways, Thanks for the GUI!

**Comment by RamyE** [comment]
Hi Ashkan,

Thanks for letting me know. I'll take a look to fix the 'pass'ed
exceptions. Can you let me know what the error message you get is?
It is fine to make local edits as long as you reboot the RPi after as the
script starts running on the background on startup. You can also kill it
and run it manually if you want.

If you have improvements to error handling and logging, please feel free to
contribute with a Pull Request! That would be appreciated!

**Comment by AshkanTavassoli** [comment]
When using the GUI to test a model(By clicking on start processing on RegressionLab) I get the error "Problem opening the current model with path SFU_ML/RPi_Script/saved_models/myModel" on the GUI.
LabTest works fine by the way.
Also, I think it would be nice if you could mention the fact that we need to upload the model to saved_models directory in the manual.
Thanks for the fast response!

**Comment by AshkanTavassoli** [comment]
And I did some local changes to find out what I am doing wrong but even the slightest changes made the program unresponsive after reboot. I probably did something wrong there so just ignore that part ;)

**Comment by RamyE** [comment]
Okay, let me add the exception message

**Comment by RamyE** [comment]
done, feel free to pull your rpi repo and test again to find the real exception

**Comment by AshkanTavassoli** [comment]
Found the problem.
Really a silly one, Model was dumped using 64 bit Python and loaded on a 32 bit one.
Might want to put that in manual just as a heads up since most people are used to 64 bit systems and might just forget the fact that we are dealing with a 32 bit system on RaspberryPi Zero.
Thanks!

**Comment by RamyE** [comment]
Yeah I have a note on the repo readme.md but makes sense to link it in the manual as well! Thanks for the heads-up. I am curious what was the exact exception/error message?

**Comment by AshkanTavassoli** [comment]
Oh i did not check readme.md, my bad.
To be honest I found the problem and fixed it before running git pull so I
did not see the error. I have some difficulty accessing the Raspberry since
I am currently in Iran and I am doing everything remotely but next time I
get access I can check out the error with a 64-bit saved model if you like.

**Comment by RamyE** [comment]
It's all good then, glad it works!
