### ISSUE TITLE
Error for Processing ~~

### ISSUE THREAD

**Issue by jnowshad** [RamyE/SFU_ML#6]
INFO: The Processing has started
INFO: Now processing: 21.732, 1064.4, 550.1, 11.155
ERROR: Acknowledgment Failed, received: EXCEPTION: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 4)
ERROR: Error processing line number 1, possible serial communication issues
ERROR: Processing has failed or was interrupted

**Comment by RamyE** [comment]
**(size 1 is different from 4)** is the key error here. The model is trained using 1 input feature and It is being fed 4 features/columns from the test data
