### ISSUE TITLE
wpa_supplicant.conf and ssh files are gone from the root file

### ISSUE THREAD

**Issue by zipal12671** [RamyE/SFU_ML#7]
I followed every step and was able to run the GUI. Today, trying to open the GUI and complete the final part of assignment 1, the RPI is not connecting to my wifi anymore.  I noticed that the wpa_supplicant.conf and ssh files are no longer in the root file. The RPi is still connecting to my PC as a serial port but not connecting to wifi, thus I cannot connect through WinSCP.

What do I do to fix this problem?

**Comment by RamyE** [comment]
The wpa_supplicant file is moved (consumed) by the RPi when it boots to the location where the RPi uses it. That said, creating a new one should replace the old one. It is normal that this file disappears (and so is the ssh file). It is likely that there was something wrong with the file provided so it just silently failed to connect to the WiFi. Please have a look at this article and pay extra attention to the EOL (in step 2). Windows have different end-of-line convention so it is likely that the Linux system (RPi) just wasn't able to parse the file correctly. https://www.raspberrypi-spy.co.uk/2017/04/manually-setting-up-pi-wifi-using-wpa_supplicant-conf/

Let me know if that solves the problem.

**Comment by RamyE** [comment]
Also, did it connect previously but isn't connecting anymore or did it never connect?

**Comment by zipal12671** [comment]
It was able to connect previously.

**Comment by RamyE** [comment]
Can you try to ssh to it using `ssh pi@raspberrypi` but reboot it first a few minutes before trying to ssh now. Let me know what output/error you get

**Comment by zipal12671** [comment]
I think I am stuck back on Step 1.2. I am in my router gateway and cant see Rpi connected to the network

**Comment by zipal12671** [comment]
![image](https://user-images.githubusercontent.com/72773536/108640623-abe3bf00-744f-11eb-8490-7e74d23535d4.png)

**Comment by zipal12671** [comment]
![image](https://user-images.githubusercontent.com/72773536/108640673-f06f5a80-744f-11eb-8c18-bbec48b01e8a.png)

**Comment by RamyE** [comment]
what is -I? can you open a command prompt in windows (`cmd`) and try to ssh using `ssh pi@raspberrypi`

Let me know what the exact error is. 🤔 After that, you can try to:
- Disconnect/unplug the RPi
- Restart your router and wait for at least 10 minutes until it is fully booted and WiFi is stable
- Plug your RPi again 
- If all of that doesn't help: Add a new wpa_supplicant.conf and try again
- If still, you may want to try a fresh image

**Comment by zipal12671** [comment]
The error i get is:

ssh: connect to host raspberrypi port 22: Connection timed out

**Comment by RamyE** [comment]
Do you have another raspberry pi on the same network?
It looks like it can recognize this hostname (which means your rpi is actually connected or you have another on on the network)

**Comment by zipal12671** [comment]
No, I dont have another raspberry pi

**Comment by RamyE** [comment]
Interesting, maybe the hostname is cached somehow. Can you try to `ping raspberrypi`

**Comment by RamyE** [comment]
can you also try again `ssh pi@raspberrypi -v` to see the debug logs

**Comment by zipal12671** [comment]
Restarting the router helped! I am now able to connect to the RPI through WinSCP. However, now I am not able to open the GUI in step 2.3. I get this error.

![image](https://user-images.githubusercontent.com/72773536/108641152-ad62b680-7452-11eb-9882-86fb9b64927e.png)

**Comment by RamyE** [comment]
you need `python` 😬

**Comment by zipal12671** [comment]
But I dont understand, I have python through the anaconda 3 program. The GUI worked before. Should I just restart the whole process? What are the steps to restart the process? Delete the SFU_ML folder?

**Comment by RamyE** [comment]
oh you just need to type `python .\Ui_Project\main.py` 😅

**Comment by zipal12671** [comment]
Yikes LOL. Ok everything is working now thank you!

**Comment by RamyE** [comment]
Great!
