### ISSUE TITLE
1.4. Clone the python script issue

### ISSUE THREAD

**Issue by ZhaoruiXu** [RamyE/SFU_ML#8]
![image](https://user-images.githubusercontent.com/79429146/108646025-764bcf80-7469-11eb-87c4-fd3e4abd8f94.png)

Hi Ramy,

I have encountered this issue shown in the screenshot, please let me know if there is a way to solve it. 

Thanks
Rui

**Comment by RamyE** [comment]
You have a typo in the command starting with echo, it should be `RPi` not
`RPI`. Please repeat that command and then you should be able to do the git
pull command again

**Comment by RamyE** [comment]
You have a typo in the command starting with echo, it should be `RPi` not `RPI`. Please repeat that command and then you should be able to do the git pull command again
